/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare8_14 (
    input z,
    input n,
    input v,
    input [1:0] alufn,
    output reg [7:0] cmp
  );
  
  
  
  reg c;
  
  always @* begin
    if (alufn == 2'h1) begin
      c = z;
    end else begin
      if (alufn == 2'h2) begin
        c = (n || v) && !(n && v);
      end else begin
        if (alufn == 2'h3) begin
          c = z || ((n || v) && !(n && v));
        end else begin
          c = 1'h0;
        end
      end
    end
    cmp[1+6-:7] = 7'h00;
    cmp[0+0-:1] = c;
  end
endmodule
