/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_22 (
    input a,
    input b,
    input cin,
    output reg sum,
    output reg cout
  );
  
  
  
  always @* begin
    sum = a ^ b ^ cin;
    cout = ((a && b) || (a && cin) || (b && cin));
  end
endmodule
