/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_grid_9 (
    input [31:0] in,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (in[24+0+1-:2])
      1'h0: begin
        out[12+3-:4] = 4'h1;
      end
      1'h1: begin
        out[12+3-:4] = 4'h2;
      end
      2'h2: begin
        out[12+3-:4] = 4'h4;
      end
      2'h3: begin
        out[12+3-:4] = 4'h8;
      end
    endcase
    
    case (in[16+0+1-:2])
      1'h0: begin
        out[8+3-:4] = 4'h1;
      end
      1'h1: begin
        out[8+3-:4] = 4'h2;
      end
      2'h2: begin
        out[8+3-:4] = 4'h4;
      end
      2'h3: begin
        out[8+3-:4] = 4'h8;
      end
    endcase
    
    case (in[8+0+1-:2])
      1'h0: begin
        out[4+3-:4] = 4'h1;
      end
      1'h1: begin
        out[4+3-:4] = 4'h2;
      end
      2'h2: begin
        out[4+3-:4] = 4'h4;
      end
      2'h3: begin
        out[4+3-:4] = 4'h8;
      end
    endcase
    
    case (in[0+0+1-:2])
      1'h0: begin
        out[0+3-:4] = 4'h1;
      end
      1'h1: begin
        out[0+3-:4] = 4'h2;
      end
      2'h2: begin
        out[0+3-:4] = 4'h4;
      end
      2'h3: begin
        out[0+3-:4] = 4'h8;
      end
    endcase
    if (in[24+7+0-:1] == 1'h1) begin
      out[12+3-:4] = 1'h0;
    end
    if (in[16+7+0-:1] == 1'h1) begin
      out[8+3-:4] = 1'h0;
    end
    if (in[8+7+0-:1] == 1'h1) begin
      out[4+3-:4] = 1'h0;
    end
    if (in[8+7+0-:1] == 1'h1) begin
      out[0+3-:4] = 1'h0;
    end
  end
endmodule
