/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_5 (
    input [3:0] in,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (in)
      4'h0: begin
        out = 8'h77;
      end
      4'h1: begin
        out = 8'h24;
      end
      4'h2: begin
        out = 8'hb3;
      end
      4'h3: begin
        out = 8'hb6;
      end
      4'h4: begin
        out = 8'hd4;
      end
      4'h5: begin
        out = 8'he6;
      end
      4'h6: begin
        out = 8'he7;
      end
      4'h7: begin
        out = 8'h34;
      end
      4'h8: begin
        out = 8'hf7;
      end
      4'h9: begin
        out = 8'hf6;
      end
      4'hf: begin
        out = 8'h67;
      end
    endcase
  end
endmodule
