/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_with_rotate_16 (
    input [7:0] a,
    input [2:0] b,
    input [3:0] alufn,
    input cin,
    output reg [7:0] out,
    output reg cout
  );
  
  
  
  reg [7:0] c;
  
  reg [2:0] xb;
  
  integer i;
  
  wire [8-1:0] M_shifter_shift;
  shift8_20 shifter (
    .a(a),
    .b(b),
    .alufn(alufn[0+1-:2]),
    .shift(M_shifter_shift)
  );
  
  wire [8-1:0] M_adder_sum;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_n;
  wire [1-1:0] M_adder_v;
  adder_17 adder (
    .a(M_shifter_shift),
    .b(c),
    .alufn(1'h0),
    .sum(M_adder_sum),
    .z(M_adder_z),
    .n(M_adder_n),
    .v(M_adder_v)
  );
  
  always @* begin
    out = M_adder_sum;
    if (alufn == 4'h4) begin
      c = 1'h0;
      for (i = 1'h0; i < b; i = i + 1) begin
        c[(i)*1+0-:1] = a[(3'h7 - i)*1+0-:1];
      end
    end else begin
      if (alufn == 4'h5) begin
        c = 1'h0;
        for (i = 1'h0; i < b; i = i + 1) begin
          c[(3'h7 - i)*1+0-:1] = a[(i)*1+0-:1];
        end
      end else begin
        if (alufn == 4'hc) begin
          cout = a[7+0-:1];
          c[0+0-:1] = cin;
          c[1+6-:7] = 1'h0;
        end else begin
          if (alufn == 4'hd) begin
            c[7+0-:1] = cin;
            c[0+6-:7] = 1'h0;
            cout = a[0+0-:1];
          end else begin
            c = 1'h0;
            cout = 1'h0;
          end
        end
      end
    end
  end
endmodule
