/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttoninputdecoder_2 (
    input clk,
    input rst,
    input reset,
    input red,
    input green,
    input blue,
    input yellow,
    input up,
    input down,
    input left,
    input right,
    input confirm,
    output reg irq,
    output reg [7:0] value
  );
  
  
  
  reg [7:0] M_buffer_d, M_buffer_q = 1'h0;
  
  always @* begin
    M_buffer_d = M_buffer_q;
    
    irq = 1'h0;
    value = M_buffer_q;
    if (red == 1'h1) begin
      M_buffer_d = 8'h00;
    end else begin
      if (green == 1'h1) begin
        M_buffer_d = 8'h01;
      end else begin
        if (blue == 1'h1) begin
          M_buffer_d = 8'h02;
        end else begin
          if (yellow == 1'h1) begin
            M_buffer_d = 8'h03;
          end else begin
            if (up == 1'h1) begin
              M_buffer_d = 8'h04;
            end else begin
              if (down == 1'h1) begin
                M_buffer_d = 8'h05;
              end else begin
                if (left == 1'h1) begin
                  M_buffer_d = 8'h06;
                end else begin
                  if (right == 1'h1) begin
                    M_buffer_d = 8'h07;
                  end else begin
                    if (confirm == 1'h1) begin
                      M_buffer_d = 8'h08;
                    end else begin
                      if (reset == 1'h1) begin
                        M_buffer_d = 8'hff;
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_buffer_q <= 1'h0;
    end else begin
      M_buffer_q <= M_buffer_d;
    end
  end
  
endmodule
