/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module programRom_4 (
    input clk,
    input rst,
    input [15:0] address,
    output reg [25:0] inst
  );
  
  
  
  always @* begin
    inst = 1'h0;
    
    case (address)
      16'h0000: begin
        inst = 26'h34038ff;
      end
      16'h0001: begin
        inst = 26'h1efc000;
      end
      16'h0002: begin
        inst = 26'h20238fc;
      end
      16'h0003: begin
        inst = 26'h0100000;
      end
      16'h0004: begin
        inst = 26'h34038ff;
      end
      16'h0005: begin
        inst = 26'h1efc004;
      end
      16'h0006: begin
        inst = 26'h20278fc;
      end
      16'h0007: begin
        inst = 26'h0100000;
      end
      16'h0008: begin
        inst = 26'h34038ff;
      end
      16'h0009: begin
        inst = 26'h1efc008;
      end
      16'h000a: begin
        inst = 26'h202b8fc;
      end
      16'h000b: begin
        inst = 26'h0100000;
      end
      16'h000c: begin
        inst = 26'h34038ff;
      end
      16'h000d: begin
        inst = 26'h1efc00c;
      end
      16'h000e: begin
        inst = 26'h202f8fc;
      end
      16'h000f: begin
        inst = 26'h0100000;
      end
      16'h0011: begin
        inst = 26'h3403808;
      end
      16'h0012: begin
        inst = 26'h1dfc011;
      end
      16'h0013: begin
        inst = 26'h0100000;
      end
      16'h0014: begin
        inst = 26'h3003f81;
      end
      16'h0015: begin
        inst = 26'h1b00000;
      end
      16'h0100: begin
        inst = 26'h3003f44;
      end
      16'h0101: begin
        inst = 26'h0303f01;
      end
      16'h0102: begin
        inst = 26'h3003f46;
      end
      16'h0103: begin
        inst = 26'h0303f01;
      end
      16'h0104: begin
        inst = 26'h3003f42;
      end
      16'h0105: begin
        inst = 26'h0303f01;
      end
      16'h0106: begin
        inst = 26'h3003f40;
      end
      16'h0107: begin
        inst = 26'h0303f01;
      end
      16'h0108: begin
        inst = 26'h3003f44;
      end
      16'h0109: begin
        inst = 26'h0303f01;
      end
      16'h010a: begin
        inst = 26'h3003f40;
      end
      16'h010b: begin
        inst = 26'h0303f01;
      end
      16'h010c: begin
        inst = 26'h3003f46;
      end
      16'h010d: begin
        inst = 26'h0303f01;
      end
      16'h010e: begin
        inst = 26'h3003f42;
      end
      16'h010f: begin
        inst = 26'h0303f01;
      end
      16'h0110: begin
        inst = 26'h3003f46;
      end
      16'h0111: begin
        inst = 26'h0303f01;
      end
      16'h0112: begin
        inst = 26'h3003f44;
      end
      16'h0113: begin
        inst = 26'h0303f01;
      end
      16'h0114: begin
        inst = 26'h3003f40;
      end
      16'h0115: begin
        inst = 26'h0303f01;
      end
      16'h0116: begin
        inst = 26'h3003f42;
      end
      16'h0117: begin
        inst = 26'h0303f01;
      end
      16'h0118: begin
        inst = 26'h3003f42;
      end
      16'h0119: begin
        inst = 26'h0303f01;
      end
      16'h011a: begin
        inst = 26'h3003f46;
      end
      16'h011b: begin
        inst = 26'h0303f01;
      end
      16'h011c: begin
        inst = 26'h3003f40;
      end
      16'h011d: begin
        inst = 26'h0303f01;
      end
      16'h011e: begin
        inst = 26'h3003f42;
      end
      16'h011f: begin
        inst = 26'h0303f01;
      end
      16'h0120: begin
        inst = 26'h3003f46;
      end
      16'h0121: begin
        inst = 26'h0303f01;
      end
      16'h0122: begin
        inst = 26'h3003f44;
      end
      16'h0123: begin
        inst = 26'h0303f01;
      end
      16'h0124: begin
        inst = 26'h3003f40;
      end
      16'h0125: begin
        inst = 26'h0303f01;
      end
      16'h0126: begin
        inst = 26'h3003f42;
      end
      16'h0127: begin
        inst = 26'h0303f01;
      end
      16'h0128: begin
        inst = 26'h3003f42;
      end
      16'h0129: begin
        inst = 26'h0303f01;
      end
      16'h012a: begin
        inst = 26'h3003f46;
      end
      16'h012b: begin
        inst = 26'h0303f01;
      end
      16'h012c: begin
        inst = 26'h3003f40;
      end
      16'h012d: begin
        inst = 26'h0303f01;
      end
      16'h012e: begin
        inst = 26'h3003f44;
      end
      16'h012f: begin
        inst = 26'h0303f01;
      end
      16'h0130: begin
        inst = 26'h3003f44;
      end
      16'h0131: begin
        inst = 26'h0303f01;
      end
      16'h0132: begin
        inst = 26'h3003f46;
      end
      16'h0133: begin
        inst = 26'h0303f01;
      end
      16'h0134: begin
        inst = 26'h3003f42;
      end
      16'h0135: begin
        inst = 26'h0303f01;
      end
      16'h0136: begin
        inst = 26'h3003f40;
      end
      16'h0137: begin
        inst = 26'h0303f01;
      end
      16'h0138: begin
        inst = 26'h3003f44;
      end
      16'h0139: begin
        inst = 26'h0303f01;
      end
      16'h013a: begin
        inst = 26'h3003f40;
      end
      16'h013b: begin
        inst = 26'h0303f01;
      end
      16'h013c: begin
        inst = 26'h3003f46;
      end
      16'h013d: begin
        inst = 26'h0303f01;
      end
      16'h013e: begin
        inst = 26'h3003f42;
      end
      16'h013f: begin
        inst = 26'h0303f01;
      end
      16'h0140: begin
        inst = 26'h3077f00;
      end
      16'h0141: begin
        inst = 26'h02f7e00;
      end
      16'h0142: begin
        inst = 26'h3077f01;
      end
      16'h0143: begin
        inst = 26'h02f7e00;
      end
      16'h0144: begin
        inst = 26'h3077f02;
      end
      16'h0145: begin
        inst = 26'h02f7e00;
      end
      16'h0146: begin
        inst = 26'h3077f03;
      end
      16'h0147: begin
        inst = 26'h02f7e00;
      end
      16'h0200: begin
        inst = 26'h3003f44;
      end
      16'h0201: begin
        inst = 26'h0303f02;
      end
      16'h0202: begin
        inst = 26'h3003f40;
      end
      16'h0203: begin
        inst = 26'h0303f02;
      end
      16'h0204: begin
        inst = 26'h3003f42;
      end
      16'h0205: begin
        inst = 26'h0303f02;
      end
      16'h0206: begin
        inst = 26'h3003f46;
      end
      16'h0207: begin
        inst = 26'h0303f02;
      end
      16'h0208: begin
        inst = 26'h3003f46;
      end
      16'h0209: begin
        inst = 26'h0303f02;
      end
      16'h020a: begin
        inst = 26'h3003f40;
      end
      16'h020b: begin
        inst = 26'h0303f02;
      end
      16'h020c: begin
        inst = 26'h3003f44;
      end
      16'h020d: begin
        inst = 26'h0303f02;
      end
      16'h020e: begin
        inst = 26'h3003f42;
      end
      16'h020f: begin
        inst = 26'h0303f02;
      end
      16'h0210: begin
        inst = 26'h3003f46;
      end
      16'h0211: begin
        inst = 26'h0303f02;
      end
      16'h0212: begin
        inst = 26'h3003f42;
      end
      16'h0213: begin
        inst = 26'h0303f02;
      end
      16'h0214: begin
        inst = 26'h3003f40;
      end
      16'h0215: begin
        inst = 26'h0303f02;
      end
      16'h0216: begin
        inst = 26'h3003f44;
      end
      16'h0217: begin
        inst = 26'h0303f02;
      end
      16'h0218: begin
        inst = 26'h3003f40;
      end
      16'h0219: begin
        inst = 26'h0303f02;
      end
      16'h021a: begin
        inst = 26'h3003f46;
      end
      16'h021b: begin
        inst = 26'h0303f02;
      end
      16'h021c: begin
        inst = 26'h3003f42;
      end
      16'h021d: begin
        inst = 26'h0303f02;
      end
      16'h021e: begin
        inst = 26'h3003f44;
      end
      16'h021f: begin
        inst = 26'h0303f02;
      end
      16'h0220: begin
        inst = 26'h3003f42;
      end
      16'h0221: begin
        inst = 26'h0303f02;
      end
      16'h0222: begin
        inst = 26'h3003f44;
      end
      16'h0223: begin
        inst = 26'h0303f02;
      end
      16'h0224: begin
        inst = 26'h3003f40;
      end
      16'h0225: begin
        inst = 26'h0303f02;
      end
      16'h0226: begin
        inst = 26'h3003f46;
      end
      16'h0227: begin
        inst = 26'h0303f02;
      end
      16'h0228: begin
        inst = 26'h3003f42;
      end
      16'h0229: begin
        inst = 26'h0303f02;
      end
      16'h022a: begin
        inst = 26'h3003f46;
      end
      16'h022b: begin
        inst = 26'h0303f02;
      end
      16'h022c: begin
        inst = 26'h3003f44;
      end
      16'h022d: begin
        inst = 26'h0303f02;
      end
      16'h022e: begin
        inst = 26'h3003f40;
      end
      16'h022f: begin
        inst = 26'h0303f02;
      end
      16'h0230: begin
        inst = 26'h3003f44;
      end
      16'h0231: begin
        inst = 26'h0303f02;
      end
      16'h0232: begin
        inst = 26'h3003f42;
      end
      16'h0233: begin
        inst = 26'h0303f02;
      end
      16'h0234: begin
        inst = 26'h3003f46;
      end
      16'h0235: begin
        inst = 26'h0303f02;
      end
      16'h0236: begin
        inst = 26'h3003f40;
      end
      16'h0237: begin
        inst = 26'h0303f02;
      end
      16'h0238: begin
        inst = 26'h3003f40;
      end
      16'h0239: begin
        inst = 26'h0303f02;
      end
      16'h023a: begin
        inst = 26'h3003f44;
      end
      16'h023b: begin
        inst = 26'h0303f02;
      end
      16'h023c: begin
        inst = 26'h3003f46;
      end
      16'h023d: begin
        inst = 26'h0303f02;
      end
      16'h023e: begin
        inst = 26'h3003f42;
      end
      16'h023f: begin
        inst = 26'h0303f02;
      end
      16'h0240: begin
        inst = 26'h3077f00;
      end
      16'h0241: begin
        inst = 26'h02f7e00;
      end
      16'h0242: begin
        inst = 26'h3077f01;
      end
      16'h0243: begin
        inst = 26'h02f7e00;
      end
      16'h0244: begin
        inst = 26'h3077f02;
      end
      16'h0245: begin
        inst = 26'h02f7e00;
      end
      16'h0246: begin
        inst = 26'h3077f03;
      end
      16'h0247: begin
        inst = 26'h02f7e00;
      end
      16'h0300: begin
        inst = 26'h3003f42;
      end
      16'h0301: begin
        inst = 26'h0303f03;
      end
      16'h0302: begin
        inst = 26'h3003f40;
      end
      16'h0303: begin
        inst = 26'h0303f03;
      end
      16'h0304: begin
        inst = 26'h3003f46;
      end
      16'h0305: begin
        inst = 26'h0303f03;
      end
      16'h0306: begin
        inst = 26'h3003f44;
      end
      16'h0307: begin
        inst = 26'h0303f03;
      end
      16'h0308: begin
        inst = 26'h3003f46;
      end
      16'h0309: begin
        inst = 26'h0303f03;
      end
      16'h030a: begin
        inst = 26'h3003f44;
      end
      16'h030b: begin
        inst = 26'h0303f03;
      end
      16'h030c: begin
        inst = 26'h3003f42;
      end
      16'h030d: begin
        inst = 26'h0303f03;
      end
      16'h030e: begin
        inst = 26'h3003f40;
      end
      16'h030f: begin
        inst = 26'h0303f03;
      end
      16'h0310: begin
        inst = 26'h3003f42;
      end
      16'h0311: begin
        inst = 26'h0303f03;
      end
      16'h0312: begin
        inst = 26'h3003f40;
      end
      16'h0313: begin
        inst = 26'h0303f03;
      end
      16'h0314: begin
        inst = 26'h3003f46;
      end
      16'h0315: begin
        inst = 26'h0303f03;
      end
      16'h0316: begin
        inst = 26'h3003f44;
      end
      16'h0317: begin
        inst = 26'h0303f03;
      end
      16'h0318: begin
        inst = 26'h3003f46;
      end
      16'h0319: begin
        inst = 26'h0303f03;
      end
      16'h031a: begin
        inst = 26'h3003f44;
      end
      16'h031b: begin
        inst = 26'h0303f03;
      end
      16'h031c: begin
        inst = 26'h3003f42;
      end
      16'h031d: begin
        inst = 26'h0303f03;
      end
      16'h031e: begin
        inst = 26'h3003f40;
      end
      16'h031f: begin
        inst = 26'h0303f03;
      end
      16'h0320: begin
        inst = 26'h3003f42;
      end
      16'h0321: begin
        inst = 26'h0303f03;
      end
      16'h0322: begin
        inst = 26'h3003f40;
      end
      16'h0323: begin
        inst = 26'h0303f03;
      end
      16'h0324: begin
        inst = 26'h3003f46;
      end
      16'h0325: begin
        inst = 26'h0303f03;
      end
      16'h0326: begin
        inst = 26'h3003f44;
      end
      16'h0327: begin
        inst = 26'h0303f03;
      end
      16'h0328: begin
        inst = 26'h3003f46;
      end
      16'h0329: begin
        inst = 26'h0303f03;
      end
      16'h032a: begin
        inst = 26'h3003f44;
      end
      16'h032b: begin
        inst = 26'h0303f03;
      end
      16'h032c: begin
        inst = 26'h3003f42;
      end
      16'h032d: begin
        inst = 26'h0303f03;
      end
      16'h032e: begin
        inst = 26'h3003f40;
      end
      16'h032f: begin
        inst = 26'h0303f03;
      end
      16'h0330: begin
        inst = 26'h3003f42;
      end
      16'h0331: begin
        inst = 26'h0303f03;
      end
      16'h0332: begin
        inst = 26'h3003f40;
      end
      16'h0333: begin
        inst = 26'h0303f03;
      end
      16'h0334: begin
        inst = 26'h3003f46;
      end
      16'h0335: begin
        inst = 26'h0303f03;
      end
      16'h0336: begin
        inst = 26'h3003f44;
      end
      16'h0337: begin
        inst = 26'h0303f03;
      end
      16'h0338: begin
        inst = 26'h3003f46;
      end
      16'h0339: begin
        inst = 26'h0303f03;
      end
      16'h033a: begin
        inst = 26'h3003f44;
      end
      16'h033b: begin
        inst = 26'h0303f03;
      end
      16'h033c: begin
        inst = 26'h3003f42;
      end
      16'h033d: begin
        inst = 26'h0303f03;
      end
      16'h033e: begin
        inst = 26'h3003f40;
      end
      16'h033f: begin
        inst = 26'h0303f03;
      end
      16'h0340: begin
        inst = 26'h3077f00;
      end
      16'h0341: begin
        inst = 26'h02f7e00;
      end
      16'h0342: begin
        inst = 26'h3077f01;
      end
      16'h0343: begin
        inst = 26'h02f7e00;
      end
      16'h0344: begin
        inst = 26'h3077f02;
      end
      16'h0345: begin
        inst = 26'h02f7e00;
      end
      16'h0346: begin
        inst = 26'h3077f03;
      end
      16'h0347: begin
        inst = 26'h02f7e00;
      end
      16'h0400: begin
        inst = 26'h3003f0e;
      end
      16'h0401: begin
        inst = 26'h0303f04;
      end
      16'h0402: begin
        inst = 26'h3003f0c;
      end
      16'h0403: begin
        inst = 26'h0303f04;
      end
      16'h0404: begin
        inst = 26'h3003f10;
      end
      16'h0405: begin
        inst = 26'h0303f04;
      end
      16'h0406: begin
        inst = 26'h3003f08;
      end
      16'h0407: begin
        inst = 26'h0303f04;
      end
      16'h0308: begin
        inst = 26'h3077f00;
      end
      16'h0309: begin
        inst = 26'h02f7e00;
      end
      16'h030a: begin
        inst = 26'h3077f01;
      end
      16'h030b: begin
        inst = 26'h02f7e00;
      end
      16'h030c: begin
        inst = 26'h3077f02;
      end
      16'h030d: begin
        inst = 26'h02f7e00;
      end
      16'h030e: begin
        inst = 26'h3077f03;
      end
      16'h030f: begin
        inst = 26'h02f7e00;
      end
      16'h8100: begin
        inst = 26'h30ebf81;
      end
      16'h8101: begin
        inst = 26'h30e7f34;
      end
      16'h8102: begin
        inst = 26'h30d3f00;
      end
      16'h8103: begin
        inst = 26'h30d7f00;
      end
      16'h8104: begin
        inst = 26'h30dbf00;
      end
      16'h8105: begin
        inst = 26'h0100000;
      end
      16'h8106: begin
        inst = 26'h34038ff;
      end
      16'h8107: begin
        inst = 26'h1ee8006;
      end
      16'h8108: begin
        inst = 26'h3403804;
      end
      16'h8109: begin
        inst = 26'h1ee8008;
      end
      16'h810a: begin
        inst = 26'h3403805;
      end
      16'h810b: begin
        inst = 26'h1ee802c;
      end
      16'h810c: begin
        inst = 26'h3403806;
      end
      16'h810d: begin
        inst = 26'h1ee8044;
      end
      16'h810e: begin
        inst = 26'h3403807;
      end
      16'h810f: begin
        inst = 26'h1ee804a;
      end
      16'h8110: begin
        inst = 26'h3403808;
      end
      16'h8111: begin
        inst = 26'h1ee8050;
      end
      16'h8112: begin
        inst = 26'h0100000;
      end
      16'h8113: begin
        inst = 26'h1bebf06;
      end
      16'h8114: begin
        inst = 26'h3403934;
      end
      16'h8115: begin
        inst = 26'h1ee801a;
      end
      16'h8116: begin
        inst = 26'h3403935;
      end
      16'h8117: begin
        inst = 26'h1ee8020;
      end
      16'h8118: begin
        inst = 26'h3403936;
      end
      16'h8119: begin
        inst = 26'h1ee8026;
      end
      16'h811a: begin
        inst = 26'h3403403;
      end
      16'h811b: begin
        inst = 26'h1ee801e;
      end
      16'h811c: begin
        inst = 26'h30d3401;
      end
      16'h811d: begin
        inst = 26'h1bebf12;
      end
      16'h811e: begin
        inst = 26'h30d3f00;
      end
      16'h811f: begin
        inst = 26'h1bebf12;
      end
      16'h8120: begin
        inst = 26'h3403503;
      end
      16'h8121: begin
        inst = 26'h1ee8024;
      end
      16'h8122: begin
        inst = 26'h30d7501;
      end
      16'h8123: begin
        inst = 26'h1bebf12;
      end
      16'h8124: begin
        inst = 26'h30d7f00;
      end
      16'h8125: begin
        inst = 26'h1bebf12;
      end
      16'h8126: begin
        inst = 26'h3403603;
      end
      16'h8127: begin
        inst = 26'h1ee802a;
      end
      16'h8128: begin
        inst = 26'h30db601;
      end
      16'h8129: begin
        inst = 26'h1bebf12;
      end
      16'h812a: begin
        inst = 26'h30dbf00;
      end
      16'h812b: begin
        inst = 26'h1bebf12;
      end
      16'h812c: begin
        inst = 26'h3403934;
      end
      16'h812d: begin
        inst = 26'h1ee8032;
      end
      16'h812e: begin
        inst = 26'h3403935;
      end
      16'h812f: begin
        inst = 26'h1ee8038;
      end
      16'h8130: begin
        inst = 26'h3403936;
      end
      16'h8131: begin
        inst = 26'h1ee803e;
      end
      16'h8132: begin
        inst = 26'h3403400;
      end
      16'h8133: begin
        inst = 26'h1ee8036;
      end
      16'h8134: begin
        inst = 26'h31d3401;
      end
      16'h8135: begin
        inst = 26'h1bebf12;
      end
      16'h8136: begin
        inst = 26'h30d3f03;
      end
      16'h8137: begin
        inst = 26'h1bebf12;
      end
      16'h8138: begin
        inst = 26'h3403500;
      end
      16'h8139: begin
        inst = 26'h1ee803c;
      end
      16'h813a: begin
        inst = 26'h31d7501;
      end
      16'h813b: begin
        inst = 26'h1bebf12;
      end
      16'h813c: begin
        inst = 26'h30d7f03;
      end
      16'h813d: begin
        inst = 26'h1bebf12;
      end
      16'h813e: begin
        inst = 26'h3403600;
      end
      16'h813f: begin
        inst = 26'h1ee8042;
      end
      16'h8140: begin
        inst = 26'h31db601;
      end
      16'h8141: begin
        inst = 26'h1bebf12;
      end
      16'h8142: begin
        inst = 26'h30dbf03;
      end
      16'h8143: begin
        inst = 26'h1bebf12;
      end
      16'h8144: begin
        inst = 26'h3403936;
      end
      16'h8145: begin
        inst = 26'h1ee8040;
      end
      16'h8146: begin
        inst = 26'h30e7901;
      end
      16'h8147: begin
        inst = 26'h1bebf12;
      end
      16'h8148: begin
        inst = 26'h30e7f34;
      end
      16'h8149: begin
        inst = 26'h1bebf12;
      end
      16'h814a: begin
        inst = 26'h3403934;
      end
      16'h814b: begin
        inst = 26'h1ee804e;
      end
      16'h814c: begin
        inst = 26'h31e7901;
      end
      16'h814d: begin
        inst = 26'h1bebf12;
      end
      16'h814e: begin
        inst = 26'h30e7f36;
      end
      16'h814f: begin
        inst = 26'h1bebf12;
      end
      16'h8150: begin
        inst = 24'h80cff4;
      end
      16'h8151: begin
        inst = 24'h80dff5;
      end
      16'h8152: begin
        inst = 24'h80eff6;
      end
      16'h8153: begin
        inst = 26'h0100000;
      end
      16'h8154: begin
        inst = 26'h3003f82;
      end
      16'h8155: begin
        inst = 26'h1b03f00;
      end
      16'h8200: begin
        inst = 26'h30ebf82;
      end
      16'h8201: begin
        inst = 26'h30e7f34;
      end
      16'h8202: begin
        inst = 26'h30d3f01;
      end
      16'h8203: begin
        inst = 26'h30d7f01;
      end
      16'h8204: begin
        inst = 26'h30dbf01;
      end
      16'h8205: begin
        inst = 26'h0100000;
      end
      16'h8206: begin
        inst = 26'h34038ff;
      end
      16'h8207: begin
        inst = 26'h1ee8006;
      end
      16'h8208: begin
        inst = 26'h3403804;
      end
      16'h8209: begin
        inst = 26'h1ee8008;
      end
      16'h820a: begin
        inst = 26'h3403805;
      end
      16'h820b: begin
        inst = 26'h1ee802c;
      end
      16'h820c: begin
        inst = 26'h3403806;
      end
      16'h820d: begin
        inst = 26'h1ee8044;
      end
      16'h820e: begin
        inst = 26'h3403807;
      end
      16'h820f: begin
        inst = 26'h1ee804a;
      end
      16'h8210: begin
        inst = 26'h3403808;
      end
      16'h8211: begin
        inst = 26'h1ee8050;
      end
      16'h8212: begin
        inst = 26'h0100000;
      end
      16'h8213: begin
        inst = 26'h1bebf06;
      end
      16'h8214: begin
        inst = 26'h3403934;
      end
      16'h8215: begin
        inst = 26'h1ee801a;
      end
      16'h8216: begin
        inst = 26'h3403935;
      end
      16'h8217: begin
        inst = 26'h1ee8020;
      end
      16'h8218: begin
        inst = 26'h3403936;
      end
      16'h8219: begin
        inst = 26'h1ee8026;
      end
      16'h821a: begin
        inst = 26'h3403403;
      end
      16'h821b: begin
        inst = 26'h1ee801e;
      end
      16'h821c: begin
        inst = 26'h30d3401;
      end
      16'h821d: begin
        inst = 26'h1bebf12;
      end
      16'h821e: begin
        inst = 26'h30d3f01;
      end
      16'h821f: begin
        inst = 26'h1bebf12;
      end
      16'h8220: begin
        inst = 26'h3403503;
      end
      16'h8221: begin
        inst = 26'h1ee8024;
      end
      16'h8222: begin
        inst = 26'h30d7501;
      end
      16'h8223: begin
        inst = 26'h1bebf12;
      end
      16'h8224: begin
        inst = 26'h30d7f01;
      end
      16'h8225: begin
        inst = 26'h1bebf12;
      end
      16'h8226: begin
        inst = 26'h3403603;
      end
      16'h8227: begin
        inst = 26'h1ee802a;
      end
      16'h8228: begin
        inst = 26'h30db601;
      end
      16'h8229: begin
        inst = 26'h1bebf12;
      end
      16'h822a: begin
        inst = 26'h30dbf01;
      end
      16'h822b: begin
        inst = 26'h1bebf12;
      end
      16'h822c: begin
        inst = 26'h3403934;
      end
      16'h822d: begin
        inst = 26'h1ee8032;
      end
      16'h822e: begin
        inst = 26'h3403935;
      end
      16'h822f: begin
        inst = 26'h1ee8038;
      end
      16'h8230: begin
        inst = 26'h3403936;
      end
      16'h8231: begin
        inst = 26'h1ee803e;
      end
      16'h8232: begin
        inst = 26'h3403401;
      end
      16'h8233: begin
        inst = 26'h1ee8036;
      end
      16'h8234: begin
        inst = 26'h31d3401;
      end
      16'h8235: begin
        inst = 26'h1bebf12;
      end
      16'h8236: begin
        inst = 26'h30d3f03;
      end
      16'h8237: begin
        inst = 26'h1bebf12;
      end
      16'h8238: begin
        inst = 26'h3403501;
      end
      16'h8239: begin
        inst = 26'h1ee803c;
      end
      16'h823a: begin
        inst = 26'h31d7501;
      end
      16'h823b: begin
        inst = 26'h1bebf12;
      end
      16'h823c: begin
        inst = 26'h30d7f03;
      end
      16'h823d: begin
        inst = 26'h1bebf12;
      end
      16'h823e: begin
        inst = 26'h3403601;
      end
      16'h823f: begin
        inst = 26'h1ee8042;
      end
      16'h8240: begin
        inst = 26'h31db601;
      end
      16'h8241: begin
        inst = 26'h1bebf12;
      end
      16'h8242: begin
        inst = 26'h30dbf03;
      end
      16'h8243: begin
        inst = 26'h1bebf12;
      end
      16'h8244: begin
        inst = 26'h3403936;
      end
      16'h8245: begin
        inst = 26'h1ee8040;
      end
      16'h8246: begin
        inst = 26'h30e7901;
      end
      16'h8247: begin
        inst = 26'h1bebf12;
      end
      16'h8248: begin
        inst = 26'h30e7f34;
      end
      16'h8249: begin
        inst = 26'h1bebf12;
      end
      16'h824a: begin
        inst = 26'h3403934;
      end
      16'h824b: begin
        inst = 26'h1ee804e;
      end
      16'h824c: begin
        inst = 26'h31e7901;
      end
      16'h824d: begin
        inst = 26'h1bebf12;
      end
      16'h824e: begin
        inst = 26'h30e7f36;
      end
      16'h824f: begin
        inst = 26'h1bebf12;
      end
      16'h8250: begin
        inst = 24'h80fff4;
      end
      16'h8251: begin
        inst = 24'h810ff5;
      end
      16'h8252: begin
        inst = 24'h811ff6;
      end
      16'h8253: begin
        inst = 26'h0100000;
      end
      16'h8254: begin
        inst = 26'h3003f83;
      end
      16'h8255: begin
        inst = 26'h1b03f00;
      end
      16'h8300: begin
        inst = 26'h30ebf83;
      end
      16'h8301: begin
        inst = 26'h3048800;
      end
      16'h8302: begin
        inst = 26'h304c900;
      end
      16'h8303: begin
        inst = 26'h3050a00;
      end
      16'h8304: begin
        inst = 26'h3054b00;
      end
      16'h8305: begin
        inst = 26'h3078c00;
      end
      16'h8306: begin
        inst = 26'h307cd00;
      end
      16'h8307: begin
        inst = 26'h3080e00;
      end
      16'h8308: begin
        inst = 26'h3075200;
      end
      16'h8309: begin
        inst = 26'h3c85e03;
      end
      16'h830a: begin
        inst = 26'h3c75d01;
      end
      16'h830b: begin
        inst = 24'h82185d;
      end
      16'h830c: begin
        inst = 26'h30f7a00;
      end
      16'h830d: begin
        inst = 26'h30fbf0f;
      end
      16'h830e: begin
        inst = 26'h023e100;
      end
      16'h830f: begin
        inst = 26'h3c85f03;
      end
      16'h8310: begin
        inst = 26'h3c75d01;
      end
      16'h8311: begin
        inst = 24'h82185d;
      end
      16'h8312: begin
        inst = 26'h30f7a00;
      end
      16'h8313: begin
        inst = 26'h30fbf15;
      end
      16'h8314: begin
        inst = 26'h0242100;
      end
      16'h8315: begin
        inst = 26'h3c86003;
      end
      16'h8316: begin
        inst = 26'h3c75d01;
      end
      16'h8317: begin
        inst = 24'h82185d;
      end
      16'h8318: begin
        inst = 26'h30f7a00;
      end
      16'h8319: begin
        inst = 26'h30fbf1b;
      end
      16'h831a: begin
        inst = 26'h0246100;
      end
      16'h831b: begin
        inst = 26'h3c85d01;
      end
      16'h831c: begin
        inst = 26'h30f7a00;
      end
      16'h831d: begin
        inst = 26'h30fbf1f;
      end
      16'h831e: begin
        inst = 26'h0387f04;
      end
      16'h831f: begin
        inst = 26'h3c86003;
      end
      16'h8320: begin
        inst = 26'h3c75d01;
      end
      16'h8321: begin
        inst = 24'h82185d;
      end
      16'h8322: begin
        inst = 26'h3086120;
      end
      16'h8323: begin
        inst = 26'h30f7a00;
      end
      16'h8324: begin
        inst = 26'h30fbf26;
      end
      16'h8325: begin
        inst = 26'h0246100;
      end
      16'h8326: begin
        inst = 26'h3c86003;
      end
      16'h8327: begin
        inst = 26'h3c75d01;
      end
      16'h8328: begin
        inst = 24'h82185d;
      end
      16'h8329: begin
        inst = 26'h3086120;
      end
      16'h832a: begin
        inst = 26'h30f7a00;
      end
      16'h832b: begin
        inst = 26'h30fbf2d;
      end
      16'h832c: begin
        inst = 26'h0242100;
      end
      16'h832d: begin
        inst = 26'h3c86003;
      end
      16'h832e: begin
        inst = 26'h3c75d01;
      end
      16'h832f: begin
        inst = 24'h82185d;
      end
      16'h8330: begin
        inst = 26'h3086120;
      end
      16'h8331: begin
        inst = 26'h30f7a00;
      end
      16'h8332: begin
        inst = 26'h30fbf34;
      end
      16'h8333: begin
        inst = 26'h023e100;
      end
      16'h8334: begin
        inst = 26'h3049d00;
      end
      16'h8335: begin
        inst = 26'h3489e03;
      end
      16'h8336: begin
        inst = 26'h1eea239;
      end
      16'h8337: begin
        inst = 26'h3079e01;
      end
      16'h8338: begin
        inst = 26'h1bebf3a;
      end
      16'h8339: begin
        inst = 26'h307bf00;
      end
      16'h833a: begin
        inst = 26'h3075300;
      end
      16'h833b: begin
        inst = 26'h3c85e03;
      end
      16'h833c: begin
        inst = 26'h3c75d01;
      end
      16'h833d: begin
        inst = 24'h82185d;
      end
      16'h833e: begin
        inst = 26'h30f7a00;
      end
      16'h833f: begin
        inst = 26'h30fbf41;
      end
      16'h8340: begin
        inst = 26'h023e100;
      end
      16'h8341: begin
        inst = 26'h3c85f03;
      end
      16'h8342: begin
        inst = 26'h3c75d01;
      end
      16'h8343: begin
        inst = 24'h82185d;
      end
      16'h8344: begin
        inst = 26'h30f7a00;
      end
      16'h8345: begin
        inst = 26'h30fbf47;
      end
      16'h8346: begin
        inst = 26'h0242100;
      end
      16'h8347: begin
        inst = 26'h3c86003;
      end
      16'h8348: begin
        inst = 26'h3c75d01;
      end
      16'h8349: begin
        inst = 24'h82185d;
      end
      16'h834a: begin
        inst = 26'h30f7a00;
      end
      16'h834b: begin
        inst = 26'h30fbf4d;
      end
      16'h834c: begin
        inst = 26'h0246100;
      end
      16'h834d: begin
        inst = 26'h3c85d01;
      end
      16'h834e: begin
        inst = 26'h30f7a00;
      end
      16'h834f: begin
        inst = 26'h30fbf51;
      end
      16'h8350: begin
        inst = 26'h0387f04;
      end
      16'h8351: begin
        inst = 26'h3c86003;
      end
      16'h8352: begin
        inst = 26'h3c75d01;
      end
      16'h8353: begin
        inst = 24'h82185d;
      end
      16'h8354: begin
        inst = 26'h3086120;
      end
      16'h8355: begin
        inst = 26'h30f7a00;
      end
      16'h8356: begin
        inst = 26'h30fbf58;
      end
      16'h8357: begin
        inst = 26'h0246100;
      end
      16'h8358: begin
        inst = 26'h3c86003;
      end
      16'h8359: begin
        inst = 26'h3c75d01;
      end
      16'h835a: begin
        inst = 24'h82185d;
      end
      16'h835b: begin
        inst = 26'h3086120;
      end
      16'h835c: begin
        inst = 26'h30f7a00;
      end
      16'h835d: begin
        inst = 26'h30fbf5f;
      end
      16'h835e: begin
        inst = 26'h0242100;
      end
      16'h835f: begin
        inst = 26'h3c86003;
      end
      16'h8360: begin
        inst = 26'h3c75d01;
      end
      16'h8361: begin
        inst = 24'h82185d;
      end
      16'h8362: begin
        inst = 26'h3086120;
      end
      16'h8363: begin
        inst = 26'h30f7a00;
      end
      16'h8364: begin
        inst = 26'h30fbf66;
      end
      16'h8365: begin
        inst = 26'h023e100;
      end
      16'h8366: begin
        inst = 26'h304dd00;
      end
      16'h8367: begin
        inst = 26'h3489e03;
      end
      16'h8368: begin
        inst = 26'h1eea26b;
      end
      16'h8369: begin
        inst = 26'h3079e01;
      end
      16'h836a: begin
        inst = 26'h1bebf6c;
      end
      16'h836b: begin
        inst = 26'h307bf00;
      end
      16'h836c: begin
        inst = 26'h3489f03;
      end
      16'h836d: begin
        inst = 26'h1eea270;
      end
      16'h836e: begin
        inst = 26'h307df01;
      end
      16'h836f: begin
        inst = 26'h1bebf71;
      end
      16'h8370: begin
        inst = 26'h307ff00;
      end
      16'h8371: begin
        inst = 26'h3075400;
      end
      16'h8372: begin
        inst = 26'h3c85e03;
      end
      16'h8372: begin
        inst = 26'h3c75d01;
      end
      16'h8374: begin
        inst = 24'h82185d;
      end
      16'h8375: begin
        inst = 26'h30f7a00;
      end
      16'h8376: begin
        inst = 26'h30fbf78;
      end
      16'h8377: begin
        inst = 26'h023e100;
      end
      16'h8378: begin
        inst = 26'h3c85f03;
      end
      16'h8379: begin
        inst = 26'h3c75d01;
      end
      16'h837a: begin
        inst = 24'h82185d;
      end
      16'h837b: begin
        inst = 26'h30f7a00;
      end
      16'h837c: begin
        inst = 26'h30fbf7e;
      end
      16'h837d: begin
        inst = 26'h0242100;
      end
      16'h837e: begin
        inst = 26'h3c86003;
      end
      16'h837f: begin
        inst = 26'h3c75d01;
      end
      16'h8380: begin
        inst = 24'h82185d;
      end
      16'h8381: begin
        inst = 26'h30f7a00;
      end
      16'h8382: begin
        inst = 26'h30fbf84;
      end
      16'h8383: begin
        inst = 26'h0246100;
      end
      16'h8384: begin
        inst = 26'h3c85d01;
      end
      16'h8385: begin
        inst = 26'h30f7a00;
      end
      16'h8386: begin
        inst = 26'h30fbf88;
      end
      16'h8387: begin
        inst = 26'h0387f04;
      end
      16'h8388: begin
        inst = 26'h3c86003;
      end
      16'h8389: begin
        inst = 26'h3c75d01;
      end
      16'h838a: begin
        inst = 24'h82185d;
      end
      16'h838b: begin
        inst = 26'h3086120;
      end
      16'h838c: begin
        inst = 26'h30f7a00;
      end
      16'h838d: begin
        inst = 26'h30fbf8f;
      end
      16'h838e: begin
        inst = 26'h0246100;
      end
      16'h838f: begin
        inst = 26'h3c86003;
      end
      16'h8390: begin
        inst = 26'h3c75d01;
      end
      16'h8391: begin
        inst = 24'h82185d;
      end
      16'h8392: begin
        inst = 26'h3086120;
      end
      16'h8393: begin
        inst = 26'h30f7a00;
      end
      16'h8394: begin
        inst = 26'h30fbf96;
      end
      16'h8395: begin
        inst = 26'h0242100;
      end
      16'h8396: begin
        inst = 26'h3c86003;
      end
      16'h8397: begin
        inst = 26'h3c75d01;
      end
      16'h8398: begin
        inst = 24'h82185d;
      end
      16'h8399: begin
        inst = 26'h3086120;
      end
      16'h839a: begin
        inst = 26'h30f7a00;
      end
      16'h839b: begin
        inst = 26'h30fbf9d;
      end
      16'h839c: begin
        inst = 26'h023e100;
      end
      16'h839d: begin
        inst = 26'h3051d00;
      end
      16'h839e: begin
        inst = 26'h3489e03;
      end
      16'h839f: begin
        inst = 26'h1eea2a2;
      end
      16'h83a0: begin
        inst = 26'h3079e01;
      end
      16'h83a1: begin
        inst = 26'h1bebfa3;
      end
      16'h83a2: begin
        inst = 26'h307bf00;
      end
      16'h83a3: begin
        inst = 26'h348a003;
      end
      16'h83a4: begin
        inst = 26'h1eea2a7;
      end
      16'h83a5: begin
        inst = 26'h3082001;
      end
      16'h83a6: begin
        inst = 26'h1bebfa8;
      end
      16'h83a7: begin
        inst = 26'h3083f00;
      end
      16'h83a8: begin
        inst = 26'h3075500;
      end
      16'h83a9: begin
        inst = 26'h3c85e03;
      end
      16'h83aa: begin
        inst = 26'h3c75d01;
      end
      16'h83ab: begin
        inst = 24'h82185d;
      end
      16'h83ac: begin
        inst = 26'h30f7a00;
      end
      16'h83ad: begin
        inst = 26'h30fbfaf;
      end
      16'h83ae: begin
        inst = 26'h023e100;
      end
      16'h83af: begin
        inst = 26'h3c85f03;
      end
      16'h83b0: begin
        inst = 26'h3c75d01;
      end
      16'h83b1: begin
        inst = 24'h82185d;
      end
      16'h83b2: begin
        inst = 26'h30f7a00;
      end
      16'h83b3: begin
        inst = 26'h30fbfb5;
      end
      16'h83b4: begin
        inst = 26'h0242100;
      end
      16'h83b5: begin
        inst = 26'h3c86003;
      end
      16'h83b6: begin
        inst = 26'h3c75d01;
      end
      16'h83b7: begin
        inst = 24'h82185d;
      end
      16'h83b8: begin
        inst = 26'h30f7a00;
      end
      16'h83b9: begin
        inst = 26'h30fbfbb;
      end
      16'h83ba: begin
        inst = 26'h0246100;
      end
      16'h83bb: begin
        inst = 26'h3c85d01;
      end
      16'h83bc: begin
        inst = 26'h30f7a00;
      end
      16'h83bd: begin
        inst = 26'h30fbfbf;
      end
      16'h83be: begin
        inst = 26'h0387f04;
      end
      16'h83bf: begin
        inst = 26'h3c86003;
      end
      16'h83c0: begin
        inst = 26'h3c75d01;
      end
      16'h83c1: begin
        inst = 24'h82185d;
      end
      16'h83c2: begin
        inst = 26'h3086120;
      end
      16'h83c3: begin
        inst = 26'h30f7a00;
      end
      16'h83c4: begin
        inst = 26'h30fbfc6;
      end
      16'h83c5: begin
        inst = 26'h0246100;
      end
      16'h83c6: begin
        inst = 26'h3c86003;
      end
      16'h83c7: begin
        inst = 26'h3c75d01;
      end
      16'h83c8: begin
        inst = 24'h82185d;
      end
      16'h83c9: begin
        inst = 26'h3086120;
      end
      16'h83ca: begin
        inst = 26'h30f7a00;
      end
      16'h83cb: begin
        inst = 26'h30fbfcd;
      end
      16'h83cc: begin
        inst = 26'h0242100;
      end
      16'h83cd: begin
        inst = 26'h3c86003;
      end
      16'h83ce: begin
        inst = 26'h3c75d01;
      end
      16'h83cf: begin
        inst = 24'h82185d;
      end
      16'h83d0: begin
        inst = 26'h3086120;
      end
      16'h83d1: begin
        inst = 26'h30f7a00;
      end
      16'h83d2: begin
        inst = 26'h30fbfd4;
      end
      16'h83d3: begin
        inst = 26'h023e100;
      end
      16'h83d4: begin
        inst = 26'h3055d00;
      end
      16'h83d5: begin
        inst = 26'h30c1200;
      end
      16'h83d6: begin
        inst = 26'h30c5300;
      end
      16'h83d7: begin
        inst = 26'h30c9400;
      end
      16'h83d8: begin
        inst = 26'h30cd500;
      end
      16'h83d9: begin
        inst = 26'h3003f84;
      end
      16'h83da: begin
        inst = 26'h1b03f00;
      end
      16'h8400: begin
        inst = 26'h30ebf84;
      end
      16'h8401: begin
        inst = 26'h30e7f34;
      end
      16'h8402: begin
        inst = 26'h30d3f00;
      end
      16'h8403: begin
        inst = 26'h30d7f00;
      end
      16'h8404: begin
        inst = 26'h30dbf00;
      end
      16'h8405: begin
        inst = 26'h0100000;
      end
      16'h8406: begin
        inst = 26'h34038ff;
      end
      16'h8407: begin
        inst = 26'h1ee8006;
      end
      16'h8408: begin
        inst = 26'h3403804;
      end
      16'h8409: begin
        inst = 26'h1ee8008;
      end
      16'h840a: begin
        inst = 26'h3403805;
      end
      16'h840b: begin
        inst = 26'h1ee802c;
      end
      16'h840c: begin
        inst = 26'h3403806;
      end
      16'h840d: begin
        inst = 26'h1ee8044;
      end
      16'h840e: begin
        inst = 26'h3403807;
      end
      16'h840f: begin
        inst = 26'h1ee804a;
      end
      16'h8410: begin
        inst = 26'h3403808;
      end
      16'h8411: begin
        inst = 26'h1ee8050;
      end
      16'h8412: begin
        inst = 26'h0100000;
      end
      16'h8413: begin
        inst = 26'h1bebf06;
      end
      16'h8414: begin
        inst = 26'h3403934;
      end
      16'h8415: begin
        inst = 26'h1ee801a;
      end
      16'h8416: begin
        inst = 26'h3403935;
      end
      16'h8417: begin
        inst = 26'h1ee8020;
      end
      16'h8418: begin
        inst = 26'h3403936;
      end
      16'h8419: begin
        inst = 26'h1ee8026;
      end
      16'h841a: begin
        inst = 26'h3403403;
      end
      16'h841b: begin
        inst = 26'h1ee801e;
      end
      16'h841c: begin
        inst = 26'h30d3401;
      end
      16'h841d: begin
        inst = 26'h1bebf12;
      end
      16'h841e: begin
        inst = 26'h30d3f00;
      end
      16'h841f: begin
        inst = 26'h1bebf12;
      end
      16'h8420: begin
        inst = 26'h3403503;
      end
      16'h8421: begin
        inst = 26'h1ee8024;
      end
      16'h8422: begin
        inst = 26'h30d7501;
      end
      16'h8423: begin
        inst = 26'h1bebf12;
      end
      16'h8424: begin
        inst = 26'h30d7f00;
      end
      16'h8425: begin
        inst = 26'h1bebf12;
      end
      16'h8426: begin
        inst = 26'h3403603;
      end
      16'h8427: begin
        inst = 26'h1ee802a;
      end
      16'h8428: begin
        inst = 26'h30db601;
      end
      16'h8429: begin
        inst = 26'h1bebf12;
      end
      16'h842a: begin
        inst = 26'h30dbf00;
      end
      16'h842b: begin
        inst = 26'h1bebf12;
      end
      16'h842c: begin
        inst = 26'h3403934;
      end
      16'h842d: begin
        inst = 26'h1ee8032;
      end
      16'h842e: begin
        inst = 26'h3403935;
      end
      16'h842f: begin
        inst = 26'h1ee8038;
      end
      16'h8430: begin
        inst = 26'h3403936;
      end
      16'h8431: begin
        inst = 26'h1ee803e;
      end
      16'h8432: begin
        inst = 26'h3403400;
      end
      16'h8433: begin
        inst = 26'h1ee8036;
      end
      16'h8434: begin
        inst = 26'h31d3401;
      end
      16'h8435: begin
        inst = 26'h1bebf12;
      end
      16'h8436: begin
        inst = 26'h30d3f03;
      end
      16'h8437: begin
        inst = 26'h1bebf12;
      end
      16'h8438: begin
        inst = 26'h3403500;
      end
      16'h8439: begin
        inst = 26'h1ee803c;
      end
      16'h843a: begin
        inst = 26'h31d7501;
      end
      16'h843b: begin
        inst = 26'h1bebf12;
      end
      16'h843c: begin
        inst = 26'h30d7f03;
      end
      16'h843d: begin
        inst = 26'h1bebf12;
      end
      16'h843e: begin
        inst = 26'h3403600;
      end
      16'h843f: begin
        inst = 26'h1ee8042;
      end
      16'h8440: begin
        inst = 26'h31db601;
      end
      16'h8441: begin
        inst = 26'h1bebf12;
      end
      16'h8442: begin
        inst = 26'h30dbf03;
      end
      16'h8443: begin
        inst = 26'h1bebf12;
      end
      16'h8444: begin
        inst = 26'h3403936;
      end
      16'h8445: begin
        inst = 26'h1ee8040;
      end
      16'h8446: begin
        inst = 26'h30e7901;
      end
      16'h8447: begin
        inst = 26'h1bebf12;
      end
      16'h8448: begin
        inst = 26'h30e7f34;
      end
      16'h8449: begin
        inst = 26'h1bebf12;
      end
      16'h844a: begin
        inst = 26'h3403934;
      end
      16'h844b: begin
        inst = 26'h1ee804e;
      end
      16'h844c: begin
        inst = 26'h31e7901;
      end
      16'h844d: begin
        inst = 26'h1bebf12;
      end
      16'h844e: begin
        inst = 26'h30e7f36;
      end
      16'h844f: begin
        inst = 26'h1bebf12;
      end
      16'h8450: begin
        inst = 24'h816ff4;
      end
      16'h8451: begin
        inst = 24'h817ff5;
      end
      16'h8452: begin
        inst = 24'h818ff6;
      end
      16'h8453: begin
        inst = 26'h0100000;
      end
      16'h8454: begin
        inst = 26'h3003f82;
      end
      16'h8455: begin
        inst = 26'h1b03f00;
      end
      16'h8500: begin
        inst = 26'h30ebf85;
      end
      16'h8501: begin
        inst = 26'h3065200;
      end
      16'h8502: begin
        inst = 26'h3069300;
      end
      16'h8503: begin
        inst = 26'h306d400;
      end
      16'h8504: begin
        inst = 26'h3071500;
      end
      16'h8505: begin
        inst = 26'h2079600;
      end
      16'h8506: begin
        inst = 26'h207d700;
      end
      16'h8507: begin
        inst = 26'h2081800;
      end
      16'h8508: begin
        inst = 26'h3075900;
      end
      16'h8509: begin
        inst = 26'h3c85e03;
      end
      16'h850a: begin
        inst = 26'h3c75d01;
      end
      16'h850b: begin
        inst = 24'h82185d;
      end
      16'h850c: begin
        inst = 24'h83dffa;
      end
      16'h850d: begin
        inst = 26'h30fbf0f;
      end
      16'h850e: begin
        inst = 26'h023e100;
      end
      16'h850f: begin
        inst = 26'h3c85f03;
      end
      16'h8510: begin
        inst = 26'h3c75d01;
      end
      16'h8511: begin
        inst = 24'h82185d;
      end
      16'h8512: begin
        inst = 24'h83dffa;
      end
      16'h8513: begin
        inst = 26'h30fbf15;
      end
      16'h8514: begin
        inst = 26'h0242100;
      end
      16'h8515: begin
        inst = 26'h3c86003;
      end
      16'h8516: begin
        inst = 26'h3c75d01;
      end
      16'h8517: begin
        inst = 24'h82185d;
      end
      16'h8518: begin
        inst = 24'h83dffa;
      end
      16'h8519: begin
        inst = 26'h30fbf1b;
      end
      16'h851a: begin
        inst = 26'h0246100;
      end
      16'h851b: begin
        inst = 24'h82175d;
      end
      16'h851c: begin
        inst = 24'h83dffa;
      end
      16'h851d: begin
        inst = 26'h30fbf1f;
      end
      16'h851e: begin
        inst = 26'h0387f04;
      end
      16'h851f: begin
        inst = 26'h3c86003;
      end
      16'h8520: begin
        inst = 26'h3c75d01;
      end
      16'h8521: begin
        inst = 24'h82185d;
      end
      16'h8522: begin
        inst = 26'h3086120;
      end
      16'h8523: begin
        inst = 24'h83dffa;
      end
      16'h8524: begin
        inst = 26'h30fbf26;
      end
      16'h8525: begin
        inst = 26'h0246100;
      end
      16'h8526: begin
        inst = 26'h3c85f03;
      end
      16'h8527: begin
        inst = 26'h3c75d01;
      end
      16'h8528: begin
        inst = 24'h82185d;
      end
      16'h8529: begin
        inst = 26'h3086120;
      end
      16'h852a: begin
        inst = 24'h83dffa;
      end
      16'h852b: begin
        inst = 26'h30fbf2d;
      end
      16'h852c: begin
        inst = 26'h0242100;
      end
      16'h852d: begin
        inst = 26'h3c85e03;
      end
      16'h852e: begin
        inst = 26'h3c75d01;
      end
      16'h852f: begin
        inst = 24'h82185d;
      end
      16'h8530: begin
        inst = 26'h3086120;
      end
      16'h8531: begin
        inst = 24'h83dffa;
      end
      16'h8532: begin
        inst = 26'h30fbf34;
      end
      16'h8533: begin
        inst = 26'h023e100;
      end
      16'h8534: begin
        inst = 24'h819fdd;
      end
      16'h8535: begin
        inst = 26'h3489e03;
      end
      16'h8536: begin
        inst = 26'h1eea239;
      end
      16'h8537: begin
        inst = 26'h3079e01;
      end
      16'h8538: begin
        inst = 26'h02ea13a;
      end
      16'h8539: begin
        inst = 26'h307bf00;
      end
      16'h853a: begin
        inst = 24'h81dfda;
      end
      16'h853b: begin
        inst = 26'h3c85e03;
      end
      16'h853c: begin
        inst = 26'h3c75d01;
      end
      16'h853d: begin
        inst = 24'h82185d;
      end
      16'h853e: begin
        inst = 24'h83dffa;
      end
      16'h853f: begin
        inst = 26'h30fbf41;
      end
      16'h8540: begin
        inst = 26'h023e100;
      end
      16'h8541: begin
        inst = 26'h3c85f03;
      end
      16'h8542: begin
        inst = 26'h3c75d01;
      end
      16'h8543: begin
        inst = 24'h82185d;
      end
      16'h8544: begin
        inst = 24'h83dffa;
      end
      16'h8545: begin
        inst = 26'h30fbf47;
      end
      16'h8546: begin
        inst = 26'h0242100;
      end
      16'h8547: begin
        inst = 26'h3c86003;
      end
      16'h8548: begin
        inst = 26'h3c75d01;
      end
      16'h8549: begin
        inst = 24'h82185d;
      end
      16'h854a: begin
        inst = 24'h83dffa;
      end
      16'h854b: begin
        inst = 26'h30fbf4d;
      end
      16'h854c: begin
        inst = 26'h0246100;
      end
      16'h854d: begin
        inst = 24'h82175d;
      end
      16'h854e: begin
        inst = 24'h83dffa;
      end
      16'h854f: begin
        inst = 26'h30fbf51;
      end
      16'h8550: begin
        inst = 26'h0387f04;
      end
      16'h8551: begin
        inst = 26'h3c86003;
      end
      16'h8552: begin
        inst = 26'h3c75d01;
      end
      16'h8553: begin
        inst = 24'h82185d;
      end
      16'h8554: begin
        inst = 26'h3086120;
      end
      16'h8555: begin
        inst = 24'h83dffa;
      end
      16'h8556: begin
        inst = 26'h30fbf58;
      end
      16'h8557: begin
        inst = 26'h0246100;
      end
      16'h8558: begin
        inst = 26'h3c85f03;
      end
      16'h8559: begin
        inst = 26'h3c75d01;
      end
      16'h855a: begin
        inst = 24'h82185d;
      end
      16'h855b: begin
        inst = 26'h3086120;
      end
      16'h855c: begin
        inst = 24'h83dffa;
      end
      16'h855d: begin
        inst = 26'h30fbf2d;
      end
      16'h855e: begin
        inst = 26'h0242100;
      end
      16'h855f: begin
        inst = 26'h3c85e03;
      end
      16'h8560: begin
        inst = 26'h3c75d01;
      end
      16'h8561: begin
        inst = 24'h82185d;
      end
      16'h8562: begin
        inst = 26'h3086120;
      end
      16'h8563: begin
        inst = 24'h83dffa;
      end
      16'h8564: begin
        inst = 26'h30fbf66;
      end
      16'h8565: begin
        inst = 26'h023e100;
      end
      16'h8566: begin
        inst = 24'h81afdd;
      end
      16'h8567: begin
        inst = 26'h3489e03;
      end
      16'h8568: begin
        inst = 26'h1eea26b;
      end
      16'h8569: begin
        inst = 26'h3079e01;
      end
      16'h856a: begin
        inst = 26'h02ebf6c;
      end
      16'h856b: begin
        inst = 26'h307bf00;
      end
      16'h856c: begin
        inst = 26'h3489f03;
      end
      16'h856d: begin
        inst = 26'h1eea270;
      end
      16'h856e: begin
        inst = 26'h307df01;
      end
      16'h856f: begin
        inst = 26'h02ebf71;
      end
      16'h8570: begin
        inst = 26'h307ff00;
      end
      16'h8571: begin
        inst = 24'h81dfdb;
      end
      16'h8572: begin
        inst = 26'h3c85e03;
      end
      16'h8573: begin
        inst = 26'h3c75d01;
      end
      16'h8574: begin
        inst = 24'h82185d;
      end
      16'h8575: begin
        inst = 24'h83dffa;
      end
      16'h8576: begin
        inst = 26'h30fbf78;
      end
      16'h8577: begin
        inst = 26'h023e100;
      end
      16'h8578: begin
        inst = 26'h3c85f03;
      end
      16'h8579: begin
        inst = 26'h3c75d01;
      end
      16'h857a: begin
        inst = 24'h82185d;
      end
      16'h857b: begin
        inst = 24'h83dffa;
      end
      16'h857c: begin
        inst = 26'h30fbf7e;
      end
      16'h857d: begin
        inst = 26'h0242100;
      end
      16'h857e: begin
        inst = 26'h3c86003;
      end
      16'h857f: begin
        inst = 26'h3c75d01;
      end
      16'h8580: begin
        inst = 24'h82185d;
      end
      16'h8581: begin
        inst = 24'h83dffa;
      end
      16'h8582: begin
        inst = 26'h30fbf84;
      end
      16'h8583: begin
        inst = 26'h0246100;
      end
      16'h8584: begin
        inst = 24'h82175d;
      end
      16'h8585: begin
        inst = 26'h20f7f88;
      end
      16'h8586: begin
        inst = 26'h30fbf88;
      end
      16'h8587: begin
        inst = 26'h0387f04;
      end
      16'h8588: begin
        inst = 26'h3c86003;
      end
      16'h8589: begin
        inst = 26'h3c75d01;
      end
      16'h858a: begin
        inst = 24'h82185d;
      end
      16'h858b: begin
        inst = 26'h3086120;
      end
      16'h858c: begin
        inst = 24'h83dffa;
      end
      16'h858d: begin
        inst = 26'h30fbf8f;
      end
      16'h858e: begin
        inst = 26'h0246100;
      end
      16'h858f: begin
        inst = 26'h3c85f03;
      end
      16'h8590: begin
        inst = 26'h3c75d01;
      end
      16'h8591: begin
        inst = 24'h82185d;
      end
      16'h8592: begin
        inst = 26'h3086120;
      end
      16'h8593: begin
        inst = 24'h83dffa;
      end
      16'h8594: begin
        inst = 26'h30fbf96;
      end
      16'h8595: begin
        inst = 26'h0242100;
      end
      16'h8596: begin
        inst = 26'h3c85e03;
      end
      16'h8597: begin
        inst = 26'h3c75d01;
      end
      16'h8598: begin
        inst = 24'h82185d;
      end
      16'h8599: begin
        inst = 26'h3086120;
      end
      16'h859a: begin
        inst = 24'h83dffa;
      end
      16'h859b: begin
        inst = 26'h30fbf9d;
      end
      16'h859c: begin
        inst = 26'h023e100;
      end
      16'h859d: begin
        inst = 24'h81bfdd;
      end
      16'h859e: begin
        inst = 26'h3489e03;
      end
      16'h859f: begin
        inst = 26'h1eea2a2;
      end
      16'h85a0: begin
        inst = 26'h3079e01;
      end
      16'h85a1: begin
        inst = 26'h02ebfa3;
      end
      16'h85a2: begin
        inst = 26'h307bf00;
      end
      16'h85a3: begin
        inst = 26'h348a003;
      end
      16'h85a4: begin
        inst = 26'h1eea2a7;
      end
      16'h85a5: begin
        inst = 26'h3082001;
      end
      16'h85a6: begin
        inst = 26'h02ea1a8;
      end
      16'h85a7: begin
        inst = 26'h3083f00;
      end
      16'h85a8: begin
        inst = 24'h81dfdc;
      end
      16'h85a9: begin
        inst = 26'h3c85e03;
      end
      16'h85aa: begin
        inst = 26'h3c75d01;
      end
      16'h85ab: begin
        inst = 24'h82185d;
      end
      16'h85ac: begin
        inst = 24'h83dffa;
      end
      16'h85ad: begin
        inst = 26'h30fbf78;
      end
      16'h85ae: begin
        inst = 26'h023e100;
      end
      16'h85af: begin
        inst = 26'h3c85f03;
      end
      16'h85b0: begin
        inst = 26'h3c75d01;
      end
      16'h85b1: begin
        inst = 24'h82185d;
      end
      16'h85b2: begin
        inst = 24'h83dffa;
      end
      16'h85b3: begin
        inst = 26'h30fbf7e;
      end
      16'h85b4: begin
        inst = 26'h0242100;
      end
      16'h85b5: begin
        inst = 26'h3c86003;
      end
      16'h85b6: begin
        inst = 26'h3c75d01;
      end
      16'h85b7: begin
        inst = 24'h82185d;
      end
      16'h85b8: begin
        inst = 24'h83dffa;
      end
      16'h85b9: begin
        inst = 26'h30fbf84;
      end
      16'h85ba: begin
        inst = 26'h0246100;
      end
      16'h85bb: begin
        inst = 24'h82175d;
      end
      16'h85bc: begin
        inst = 24'h83dffa;
      end
      16'h85bd: begin
        inst = 26'h30fbf88;
      end
      16'h85be: begin
        inst = 26'h0387f04;
      end
      16'h85bf: begin
        inst = 26'h3c86003;
      end
      16'h85c0: begin
        inst = 26'h3c75d01;
      end
      16'h85c1: begin
        inst = 24'h82185d;
      end
      16'h85c2: begin
        inst = 26'h3086120;
      end
      16'h85c3: begin
        inst = 24'h83dffa;
      end
      16'h85c4: begin
        inst = 26'h30fbf8f;
      end
      16'h85c5: begin
        inst = 26'h0246100;
      end
      16'h85c6: begin
        inst = 26'h3c85f03;
      end
      16'h85c7: begin
        inst = 26'h3c75d01;
      end
      16'h85c8: begin
        inst = 24'h82185d;
      end
      16'h85c9: begin
        inst = 26'h3086120;
      end
      16'h85ca: begin
        inst = 24'h83dffa;
      end
      16'h85cb: begin
        inst = 26'h30fbf96;
      end
      16'h85cd: begin
        inst = 26'h0242100;
      end
      16'h85ce: begin
        inst = 26'h3c85e03;
      end
      16'h85cf: begin
        inst = 26'h3c75d01;
      end
      16'h85d0: begin
        inst = 24'h82185d;
      end
      16'h85d1: begin
        inst = 26'h3086120;
      end
      16'h85d2: begin
        inst = 24'h83dffa;
      end
      16'h85d3: begin
        inst = 26'h30fbf9d;
      end
      16'h85d4: begin
        inst = 26'h023e100;
      end
      16'h85d5: begin
        inst = 24'h81cfdd;
      end
      16'h85d6: begin
        inst = 26'h03fff88;
      end
      16'h8600: begin
        inst = 26'h30ebf86;
      end
      16'h8601: begin
        inst = 26'h30c1800;
      end
      16'h8602: begin
        inst = 26'h30c5900;
      end
      16'h8603: begin
        inst = 26'h30c9a00;
      end
      16'h8604: begin
        inst = 26'h30cdb00;
      end
      16'h8605: begin
        inst = 26'h3402d04;
      end
      16'h8606: begin
        inst = 26'h1ee800e;
      end
      16'h8607: begin
        inst = 26'h31df701;
      end
      16'h8608: begin
        inst = 26'h3403700;
      end
      16'h8609: begin
        inst = 26'h1ee800f;
      end
      16'h860a: begin
        inst = 26'h3403808;
      end
      16'h860b: begin
        inst = 26'h1ee8010;
      end
      16'h860c: begin
        inst = 26'h0100000;
      end
      16'h860d: begin
        inst = 26'h1bebf0a;
      end
      16'h860e: begin
        inst = 26'h1bfff00;
      end
      16'h860f: begin
        inst = 26'h1bfff00;
      end
      16'h8610: begin
        inst = 26'h03fff84;
      end
      16'h8800: begin
        inst = 26'h30ebf88;
      end
      16'h8801: begin
        inst = 26'h2093f20;
      end
      16'h8802: begin
        inst = 26'h2097f24;
      end
      16'h8803: begin
        inst = 26'h209bf28;
      end
      16'h8804: begin
        inst = 26'h209ff2c;
      end
      16'h8805: begin
        inst = 26'h20a3f64;
      end
      16'h8806: begin
        inst = 26'h20a7f68;
      end
      16'h8807: begin
        inst = 26'h20abf6c;
      end
      16'h8808: begin
        inst = 26'h20aff70;
      end
      16'h8809: begin
        inst = 26'h20b3ffc;
      end
      16'h880a: begin
        inst = 26'h20b7ffc;
      end
      16'h880b: begin
        inst = 26'h20bbffc;
      end
      16'h880c: begin
        inst = 26'h24b24a0;
      end
      16'h880d: begin
        inst = 26'h1eeac1d;
      end
      16'h880e: begin
        inst = 26'h24b25a4;
      end
      16'h880f: begin
        inst = 26'h1eeac21;
      end
      16'h8810: begin
        inst = 26'h24b26a8;
      end
      16'h8811: begin
        inst = 26'h1eeac25;
      end
      16'h8812: begin
        inst = 26'h24b27ac;
      end
      16'h8813: begin
        inst = 26'h1eeac29;
      end
      16'h8814: begin
        inst = 26'h34b28ff;
      end
      16'h8815: begin
        inst = 26'h1deac2d;
      end
      16'h8816: begin
        inst = 26'h34b29ff;
      end
      16'h8817: begin
        inst = 26'h1deac40;
      end
      16'h8818: begin
        inst = 26'h34b2aff;
      end
      16'h8819: begin
        inst = 26'h1deac53;
      end
      16'h881a: begin
        inst = 26'h34b2bff;
      end
      16'h881b: begin
        inst = 26'h1deac66;
      end
      16'h881c: begin
        inst = 26'h1bebf78;
      end
      16'h881d: begin
        inst = 26'h30a3fff;
      end
      16'h881e: begin
        inst = 26'h3093fff;
      end
      16'h881f: begin
        inst = 26'h30b6d01;
      end
      16'h8820: begin
        inst = 26'h1bebf0e;
      end
      16'h8821: begin
        inst = 26'h30a7fff;
      end
      16'h8822: begin
        inst = 26'h3097fff;
      end
      16'h8823: begin
        inst = 26'h30b6d01;
      end
      16'h8824: begin
        inst = 26'h1bebf10;
      end
      16'h8825: begin
        inst = 26'h30abfff;
      end
      16'h8826: begin
        inst = 26'h309bfff;
      end
      16'h8827: begin
        inst = 26'h30b6d01;
      end
      16'h8828: begin
        inst = 26'h1bebf12;
      end
      16'h8829: begin
        inst = 26'h30affff;
      end
      16'h882a: begin
        inst = 26'h309ffff;
      end
      16'h882b: begin
        inst = 26'h30b6d01;
      end
      16'h882c: begin
        inst = 26'h1bebf12;
      end
      16'h882d: begin
        inst = 26'h24b2894;
      end
      16'h882e: begin
        inst = 26'h1eeac34;
      end
      16'h882f: begin
        inst = 26'h24b2898;
      end
      16'h8830: begin
        inst = 26'h1eeac38;
      end
      16'h8831: begin
        inst = 26'h24b289c;
      end
      16'h8832: begin
        inst = 26'h1eeac3c;
      end
      16'h8833: begin
        inst = 26'h1bebf16;
      end
      16'h8834: begin
        inst = 26'h30a3fff;
      end
      16'h8835: begin
        inst = 26'h3097fff;
      end
      16'h8836: begin
        inst = 26'h30bae01;
      end
      16'h8837: begin
        inst = 26'h1bebf16;
      end
      16'h8838: begin
        inst = 26'h30a3fff;
      end
      16'h8839: begin
        inst = 26'h309bfff;
      end
      16'h883a: begin
        inst = 26'h30bae01;
      end
      16'h883b: begin
        inst = 26'h1bebf16;
      end
      16'h883c: begin
        inst = 26'h30a3fff;
      end
      16'h883d: begin
        inst = 26'h309ffff;
      end
      16'h883e: begin
        inst = 26'h30bae01;
      end
      16'h883f: begin
        inst = 26'h1bebf16;
      end
      16'h8840: begin
        inst = 26'h24b2990;
      end
      16'h8841: begin
        inst = 26'h1eeac47;
      end
      16'h8842: begin
        inst = 26'h24b2998;
      end
      16'h8843: begin
        inst = 26'h1eeac4b;
      end
      16'h8844: begin
        inst = 26'h24b299c;
      end
      16'h8845: begin
        inst = 26'h1eeac4f;
      end
      16'h8846: begin
        inst = 26'h1bebf18;
      end
      16'h8847: begin
        inst = 26'h30a7fff;
      end
      16'h8848: begin
        inst = 26'h3093fff;
      end
      16'h8849: begin
        inst = 26'h30bae01;
      end
      16'h884a: begin
        inst = 26'h1bebf18;
      end
      16'h884b: begin
        inst = 26'h30a7fff;
      end
      16'h884c: begin
        inst = 26'h309bfff;
      end
      16'h884d: begin
        inst = 26'h30bae01;
      end
      16'h884e: begin
        inst = 26'h1bebf18;
      end
      16'h884f: begin
        inst = 26'h30a7fff;
      end
      16'h8850: begin
        inst = 26'h309ffff;
      end
      16'h8851: begin
        inst = 26'h30bae01;
      end
      16'h8852: begin
        inst = 26'h1bebf18;
      end
      16'h8853: begin
        inst = 26'h24b2a90;
      end
      16'h8854: begin
        inst = 26'h1eeac5a;
      end
      16'h8855: begin
        inst = 26'h24b2a94;
      end
      16'h8856: begin
        inst = 26'h1eeac5e;
      end
      16'h8857: begin
        inst = 26'h24b2a9c;
      end
      16'h8858: begin
        inst = 26'h1eeac62;
      end
      16'h8859: begin
        inst = 26'h1bebf1a;
      end
      16'h885a: begin
        inst = 26'h30abfff;
      end
      16'h885b: begin
        inst = 26'h3093fff;
      end
      16'h885c: begin
        inst = 26'h30bae01;
      end
      16'h885d: begin
        inst = 26'h1bebf1a;
      end
      16'h885e: begin
        inst = 26'h30abfff;
      end
      16'h885f: begin
        inst = 26'h3097fff;
      end
      16'h8860: begin
        inst = 26'h30bae01;
      end
      16'h8861: begin
        inst = 26'h1bebf1a;
      end
      16'h8862: begin
        inst = 26'h30abfff;
      end
      16'h8863: begin
        inst = 26'h309ffff;
      end
      16'h8864: begin
        inst = 26'h30bae01;
      end
      16'h8865: begin
        inst = 26'h1bebf1a;
      end
      16'h8866: begin
        inst = 26'h24b2b90;
      end
      16'h8867: begin
        inst = 26'h1eeac6d;
      end
      16'h8868: begin
        inst = 26'h24b2b94;
      end
      16'h8869: begin
        inst = 26'h1eeac71;
      end
      16'h886a: begin
        inst = 26'h24b2b98;
      end
      16'h886b: begin
        inst = 26'h1eeac75;
      end
      16'h886c: begin
        inst = 26'h1bebf78;
      end
      16'h886d: begin
        inst = 26'h30affff;
      end
      16'h886e: begin
        inst = 26'h3093fff;
      end
      16'h886f: begin
        inst = 26'h30bae01;
      end
      16'h8870: begin
        inst = 26'h1bebf78;
      end
      16'h8871: begin
        inst = 26'h30affff;
      end
      16'h8872: begin
        inst = 26'h3097fff;
      end
      16'h8873: begin
        inst = 26'h30bae01;
      end
      16'h8874: begin
        inst = 26'h1bebf78;
      end
      16'h8875: begin
        inst = 26'h30affff;
      end
      16'h8876: begin
        inst = 26'h309bfff;
      end
      16'h8877: begin
        inst = 26'h30bae01;
      end
      16'h8878: begin
        inst = 26'h03fff86;
      end
    endcase
  end
endmodule
